version: '3.8'

services:
   app:
      build:
         context: .
         dockerfile: docker/Dockerfile
      ports:
         - "8080:8080"
      environment:
         SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
         SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
         SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
         SECRET_KEY: ${SECRET_KEY}
      depends_on:
         - db

   db:
      image: postgres:17.2
      container_name: postgres
      restart: always
      ports:
         - "5432:5432"
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
         - ./docker/postgres_data:/var/lib/postgresql/data
         - ./docker/sql:/docker-entrypoint-initdb.d

   nginx:
      image: nginx:1.26
      ports:
         - "80:80"
      volumes:
         - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
         - app

volumes:
   postgres_data:
